Mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import  views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('profile/', user_views.profilepage, name="profile"),
]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name="index"),
    path('<int:pk>/', views.FoodDetail.as_view(), name="detail"),
    path('add/', views.CreateItem.as_view(), name="create_item"),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.TextField(max_length=200)
    item_desc = models.TextField(max_length=200)
    item_price = models.IntegerField()

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_prictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class Register(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Item
from .form import Item_form
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.



# def index(request):
#     item_lst = item.objects.all()
#     template = loader.get_template('./food/index.html')
#     context = {
#         'item_lst': item_lst,
#     }
#     return HttpResponse(template.render(context, request))
def index(request):
    item_lst = Item.objects.all()
    # template = loader.get_template('./food/index.html')
    context = {
        'item_lst': item_lst,
    }
    return render(request, './food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    # queryset = Item.objects.all()
    context_object_name = 'item_lst'


def detail(request, item_id):
    item_ = Item.objects.get(pk=item_id)
    context = {
        'item': item_
    }
    return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


def create_item(request):
    form = Item_form(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user()

        return super().form_valid(form)
    


def update_item(request, id):
    item = Item.objects.get(id = id)
    form = Item_form(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form, 'item':item})


def delete_item(request, id):
    item = Item.objects.get(id= id)
    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item': item})
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import Register
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = Register(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, you acount is created')
            return redirect('login')
    else:
        form = Register()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{object.item_name}}</h1>
    <h2>{{object.item_desc}}</h2>
    <h2>{{object.item_price}}</h2>
    <a href="{% url 'food:delete_item' item.id %}">Delete</a>
</body>
</html>

food/templates/food/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/food/tailwind-output.css'%}">
</head>
<body>
    <h1 class="text-2xl">This is the header</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'profile' %}">Profile</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <p>{% for item in item_lst %}
        <ul>
            <li> 
                <!-- <a href="{{item.id}}">{{item.id}} {{item.item_name}}</a> -->
                <a href="{% url 'food:detail' item.id %}">{{item.id}} {{item.item_name}} {{item.user_name}}</a>
                
            </li>
        </ul>
        {% endfor %}</p>
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
</body>
</html>

food/templates/food/item-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete {{ item.item_name }}</h2>
        <button type="submit">Confirm</button>
    </form>
</body>
</html>

food/templates/food/item-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Save</button>
    </form>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>You have been logged out</h1>
</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url }}" width="300px" alt="">
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>